//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIdProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enroll
    {
        public int E_Id { get; set; }
        public int Course_Id { get; set; }
        public int Instructor_Id { get; set; }
        public string Student_Email { get; set; }
        public string Date_Of_Enrollment { get; set; }
        public string Date_Of_Completion { get; set; }
        public string Status { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual User User { get; set; }
    }
}
