//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIdProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financial
    {
        public int F_Id { get; set; }
        public int Invoice_Id { get; set; }
        public string Courses { get; set; }
        public int Paid_By { get; set; }
        public int Amount { get; set; }
        public double Profit { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
