//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIdProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int N_Id { get; set; }
        public string Notify_Name { get; set; }
        public string Notify_No { get; set; }
        public System.DateTime AddedOn { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
    }
}
